spring.application.name=activity01
spring.jpa.hibernate.ddl-auto=create
spring.datasource.url=jdbc:mysql://localhost:3307/UserAccount
spring.datasource.username=L23Y19W43
spring.datasource.password=midnightsin12
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
jwt.secret=EhbhZ8JtzHfJCqNiHGdZ0T/hM34epNdQ7Hq2HaNSJ00=
